### ISSUE TITLE
Spawning bots breaks the scoreboard.

### ISSUE THREAD

**Issue by Sketchy77** [Decicus/TTT-Scoreboard-Ranks-for-ULX#1]
When spawning bots through the ulx menu, the scoreboard breaks and gives the following error:

[ERROR] gamemodes/terrortown/gamemode/vgui/sb_row.lua:165: bad argument #1 to 'SetText' (string expected, got nil)
1. SetText - [C]:-1
   1. UpdatePlayerData - gamemodes/terrortown/gamemode/vgui/sb_row.lua:165
   2. SetPlayer - gamemodes/terrortown/gamemode/vgui/sb_row.lua:153
      1. AddPlayerRow - gamemodes/terrortown/gamemode/vgui/sb_team.lua:97
      2. UpdateScoreboard - gamemodes/terrortown/gamemode/vgui/sb_main.lua:292
      3. unknown - gamemodes/terrortown/gamemode/cl_scoreboard.lua:40

**Comment by Decicus** [comment]
What addon are you using to spawn bots with in ULX?
I tried both [Custom ULX Commands](http://forums.ulyssesmod.net/index.php/topic,7268.0.html) and using the console command "bot" via RCON on a clean server with only ULib, ULX and the addon without getting any errors.
