### ISSUE TITLE
Breaks scoreboard

### ISSUE THREAD

**Issue by untrainAssassin** [Decicus/TTT-Scoreboard-Ranks-for-ULX#3]
[ERROR] addons/ttt-scoreboard-ranks-for-ulx-master/lua/ulx/modules/sh/ttt_sb_ranks.lua:218: ')' expected near '='
1. unknown - addons/ttt-scoreboard-ranks-for-ulx-master/lua/ulx/modules/sh/ttt_sb_ranks.lua:0

**Comment by Decicus** [comment]
It doesn't seem like you're using [Version 1.1](https://github.com/Decicus/TTT-Scoreboard-Ranks-for-ULX/releases/tag/1.1). Please install this and see if the problem persists.

**Comment by untrainAssassin** [comment]
I downloaded it from here.
"AddonInfo"
{
    "name"                "TTT Scoreboard Ranks for ULX"
    "version"            "1.1"
    "up_date"            "2015-09-08"
    "author_name"            "Alex (Decicus) Thomassen"
    "author_email"            "alex@thomassen.xyz"
    "author_url"            "https://www.thomassen.xyz/"
    "info"                "Gamemode commands"
    "override"          "0"
}

**Comment by Decicus** [comment]
That's the latest addon.txt, but due to the folder name of the addon you installed, it seems you got it directly from the repository instead of installing via the "[Releases](https://github.com/Decicus/TTT-Scoreboard-Ranks-for-ULX/releases)" tab.
