### ISSUE TITLE
Ranks not showing up

### ISSUE THREAD

**Issue by meckado** [Decicus/TTT-Scoreboard-Ranks-for-ULX#4]
Hi, when I set up the ranks, I see the Rank section in the scoreboard but the name of the ranks do not appear, also I can change the width and other settings like that, but it stays empty in the Rank section. I tried removing some addons to see if that was the problem, seems like it wasn't so I really don't know what to do.

Thanks.

**Comment by Decicus** [comment]
I'm not sure what could cause this.

What version did you get? Did you use "Download ZIP" or did you get one from the "Releases" section?
If you got one from the Releases section, I would like a screenshot and possibly the contents of the "ranks.txt" file inside /data/ttt_sb_ranks/ranks.txt

If you were using the "download ZIP" option (or cloning from git), then try using one of the releases as the ones not in "releases" are not fully tested.

**Comment by meckado** [comment]
I can't seem to find the ranks.txt file, that might be why its not showing up, can you be more specific on the path of that file ? Also im using the latest version 1.1

**Comment by Decicus** [comment]
The path should be inside the base server "garrysmod" directory. So I suppose it's -garrysmod directory-/data/ttt_sb_ranks/ranks.txt.

Also, I forgot to mention this, but does any console error occur (either on the server or client) when attempting to add a rank?

**Comment by meckado** [comment]
this is what is inside the file: 

{"STEAM_0:0:49155870":{"b":0,"color":"rainbow","r":0,"text":"Owner","g":0}}    

I reinstalled the addon a couple times thats why there is only one rank, and also there is no console errors when adding a rank

**Comment by Decicus** [comment]
That seems correct, hmm.

Is it only custom ranks, or all ranks (even default ones) together not displaying?

**Comment by meckado** [comment]
Default ranks dont show up either, this is extremely weird.

**Comment by Decicus** [comment]
I'm gonna run a few tests on a local server and see if I get the same issue.

**Comment by meckado** [comment]
Ok thank you.

**Comment by Decicus** [comment]
I just tried it on a server with only ULib and ULX (+ this addon) and it seems to work fine with default ranks and setting a custom one.

I'm sorry to admit that I don't know exactly what your issue could be.

**Comment by meckado** [comment]
I just wish other players had this issue, ive been searching for a long time for a solution. Thanks for trying at least. It must be another addon thats causing this.

**Comment by meckado** [comment]
I tried this instead, im getting the same issue sadly. https://facepunch.com/showthread.php?t=1356376

**Comment by Decicus** [comment]
Hmm. Are your TTT files fully up-to-date? Have you edited the default ones in -garrysmod directory-/gamemodes/terrortown?

**Comment by meckado** [comment]
I made the server recently and updated it, so it should be the latest version.

**Comment by meckado** [comment]
Also, I didn't change anything in the ttt files, everything is in the addons folder.

**Comment by Decicus** [comment]
Yeah, that's pretty weird.

One last thing you could try, but since you had issues with a different addon that works similarly, is to run "ulx refreshranks" when loaded into the server and see if that does anything at all.

**Comment by meckado** [comment]
I've done that several times, didn't change anything, I guess I'm not gonna use scoreboard ranks for my server lol.

**Comment by Decicus** [comment]
Yeah, sorry about that dude. I just have no clue what could be causing the issue.

I'll close this for now, if that's alright with you.
